version: '3'

services:
  neo4j:
    image: neo4j:5.17.0-community
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${USER_DB}/${PASSWORD_DB}
    volumes:
      - /home/user/data:/data

  fastapi:
    image: baksbanny/blockchair-transactions:v1.0.1
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
